// <auto-generated />
using System;
using CherryPlayServer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CherryPlayServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260303092049_AddPartyEndDateTime")]
    partial class AddPartyEndDateTime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CherryPlayServer.Infrastructure.Persistence.Entities.EmailAccountEf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizer_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_email_accounts");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_email_accounts_email");

                    b.HasIndex("OrganizerId")
                        .HasDatabaseName("ix_email_accounts_organizer_id");

                    b.ToTable("email_accounts", (string)null);
                });

            modelBuilder.Entity("CherryPlayServer.Infrastructure.Persistence.Entities.OAuthAccountEf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizer_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderUserAvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("provider_user_avatar_url");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("provider_user_id");

                    b.Property<string>("ProviderUserName")
                        .HasColumnType("text")
                        .HasColumnName("provider_user_name");

                    b.HasKey("Id")
                        .HasName("pk_oauth_accounts");

                    b.HasIndex("OrganizerId")
                        .HasDatabaseName("ix_oauth_accounts_organizer_id");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_oauth_accounts_provider_provider_user_id");

                    b.ToTable("oauth_accounts", (string)null);
                });

            modelBuilder.Entity("CherryPlayServer.Infrastructure.Persistence.Entities.OrganizerEf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultCustomizationSettingsJson")
                        .HasColumnType("text")
                        .HasColumnName("default_customization_settings_json");

                    b.Property<string>("DefaultPartyThemeId")
                        .HasColumnType("text")
                        .HasColumnName("default_party_theme_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("LinksJson")
                        .HasColumnType("text")
                        .HasColumnName("links_json");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("TimeZone")
                        .HasColumnType("text")
                        .HasColumnName("time_zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_organizers");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_organizers_is_deleted");

                    b.ToTable("organizers", (string)null);
                });

            modelBuilder.Entity("CherryPlayServer.Infrastructure.Persistence.Entities.OrganizerSessionEf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizer_id");

                    b.HasKey("Id")
                        .HasName("pk_organizer_sessions");

                    b.HasIndex("OrganizerId")
                        .HasDatabaseName("ix_organizer_sessions_organizer_id");

                    b.ToTable("organizer_sessions", (string)null);
                });

            modelBuilder.Entity("CherryPlayServer.Infrastructure.Persistence.Entities.PartyEf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomizationSettingsJson")
                        .HasColumnType("text")
                        .HasColumnName("customization_settings_json");

                    b.Property<string>("DanceTagsJson")
                        .HasColumnType("text")
                        .HasColumnName("dance_tags_json");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EventDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_date_time");

                    b.Property<DateTime?>("EventEndDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_end_date_time");

                    b.Property<string>("ExternalLinkText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_link_text");

                    b.Property<string>("ExternalLinkUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("external_link_url");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsListedInCatalog")
                        .HasColumnType("boolean")
                        .HasColumnName("is_listed_in_catalog");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizer_id");

                    b.Property<string>("PartyThemeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("party_theme_id");

                    b.Property<string>("Place")
                        .HasColumnType("text")
                        .HasColumnName("place");

                    b.Property<string>("Schedule")
                        .HasColumnType("text")
                        .HasColumnName("schedule");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("short_code");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("short_description");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("subtitle");

                    b.Property<string>("TimeZone")
                        .HasColumnType("text")
                        .HasColumnName("time_zone");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_parties");

                    b.HasIndex("IsListedInCatalog")
                        .HasDatabaseName("ix_parties_is_listed_in_catalog");

                    b.HasIndex("OrganizerId")
                        .HasDatabaseName("ix_parties_organizer_id");

                    b.HasIndex("ShortCode")
                        .IsUnique()
                        .HasDatabaseName("ix_parties_short_code");

                    b.ToTable("parties", (string)null);
                });

            modelBuilder.Entity("CherryPlayServer.Infrastructure.Persistence.Entities.PartyPlaylistEf", b =>
                {
                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("party_id");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("items");

                    b.Property<int>("TotalDuration")
                        .HasColumnType("integer")
                        .HasColumnName("total_duration");

                    b.Property<int>("TotalTracks")
                        .HasColumnType("integer")
                        .HasColumnName("total_tracks");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PartyId")
                        .HasName("pk_party_playlists");

                    b.ToTable("party_playlists", (string)null);
                });

            modelBuilder.Entity("CherryPlayServer.Infrastructure.Persistence.Entities.SessionStateEf", b =>
                {
                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("party_id");

                    b.Property<string>("CurrentTrackId")
                        .HasColumnType("text")
                        .HasColumnName("current_track_id");

                    b.Property<string>("DisabledGroupIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("disabled_group_ids");

                    b.Property<string>("DisabledTrackIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("disabled_track_ids");

                    b.Property<double>("Duration")
                        .HasColumnType("double precision")
                        .HasColumnName("duration");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mode");

                    b.Property<string>("PlayedTrackIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("played_track_ids");

                    b.Property<double>("Position")
                        .HasColumnType("double precision")
                        .HasColumnName("position");

                    b.Property<DateTime?>("SessionStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("session_started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<double>("Volume")
                        .HasColumnType("double precision")
                        .HasColumnName("volume");

                    b.HasKey("PartyId")
                        .HasName("pk_session_states");

                    b.ToTable("session_states", (string)null);
                });

            modelBuilder.Entity("CherryPlayServer.Infrastructure.Persistence.Entities.EmailAccountEf", b =>
                {
                    b.HasOne("CherryPlayServer.Infrastructure.Persistence.Entities.OrganizerEf", "Organizer")
                        .WithMany("EmailAccounts")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_accounts_organizers_organizer_id");

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("CherryPlayServer.Infrastructure.Persistence.Entities.OAuthAccountEf", b =>
                {
                    b.HasOne("CherryPlayServer.Infrastructure.Persistence.Entities.OrganizerEf", "Organizer")
                        .WithMany("OAuthAccounts")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_oauth_accounts_organizers_organizer_id");

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("CherryPlayServer.Infrastructure.Persistence.Entities.OrganizerSessionEf", b =>
                {
                    b.HasOne("CherryPlayServer.Infrastructure.Persistence.Entities.OrganizerEf", "Organizer")
                        .WithMany("Sessions")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organizer_sessions_organizers_organizer_id");

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("CherryPlayServer.Infrastructure.Persistence.Entities.PartyEf", b =>
                {
                    b.HasOne("CherryPlayServer.Infrastructure.Persistence.Entities.OrganizerEf", "Organizer")
                        .WithMany("Parties")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_parties_organizers_organizer_id");

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("CherryPlayServer.Infrastructure.Persistence.Entities.PartyPlaylistEf", b =>
                {
                    b.HasOne("CherryPlayServer.Infrastructure.Persistence.Entities.PartyEf", "Party")
                        .WithOne("Playlist")
                        .HasForeignKey("CherryPlayServer.Infrastructure.Persistence.Entities.PartyPlaylistEf", "PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_party_playlists_parties_party_id");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("CherryPlayServer.Infrastructure.Persistence.Entities.SessionStateEf", b =>
                {
                    b.HasOne("CherryPlayServer.Infrastructure.Persistence.Entities.PartyEf", "Party")
                        .WithOne("SessionState")
                        .HasForeignKey("CherryPlayServer.Infrastructure.Persistence.Entities.SessionStateEf", "PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_session_states_parties_party_id");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("CherryPlayServer.Infrastructure.Persistence.Entities.OrganizerEf", b =>
                {
                    b.Navigation("EmailAccounts");

                    b.Navigation("OAuthAccounts");

                    b.Navigation("Parties");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("CherryPlayServer.Infrastructure.Persistence.Entities.PartyEf", b =>
                {
                    b.Navigation("Playlist");

                    b.Navigation("SessionState");
                });
#pragma warning restore 612, 618
        }
    }
}
