services:
  postgres:
    dns:
      - 8.8.8.8
      - 1.1.1.1
  pgadmin:
    dns:
      - 8.8.8.8
      - 1.1.1.1
  migrate:
    dns:
      - 8.8.8.8
      - 1.1.1.1
  server:
    dns:
      - 8.8.8.8
      - 1.1.1.1
  web:
    dns:
      - 8.8.8.8
      - 1.1.1.1
