import { useMemo } from 'react';

import { useProjectStore, useUIStore } from '@shared/stores';
import { useOnlineNetworkPolicy } from '@shared/streaming';

import { usePartyWorkspaceStore } from './partyWorkspaceStore';
import { usePartyPlaylistState } from './usePartyPlaylistState';
import { usePartyServerActions, usePartyWorkspaceAuthState } from './usePartyServerActions';
import { usePartyWorkspaceEffects } from './usePartyWorkspaceEffects';

export function usePartyWorkspaceRuntime() {
  const { isAuth, isClientOutdated, clientRequiredVersion } = usePartyWorkspaceAuthState();
  const { networkEnabled } = useOnlineNetworkPolicy();

  const meta = useProjectStore((state) => state.meta);
  const setPartyTrackDisplaySettings = useProjectStore(
    (state) => state.setPartyTrackDisplaySettings,
  );

  const {
    partyName,
    partyTitle,
    partySubtitle,
    themeId,
    customizationSettings,
    eventDateTime,
    eventEndDateTime,
    description,
    place,
    city,
    schedule,
    timeZone,
    shortDescription,
    externalLinkUrl,
    externalLinkText,
    danceTags,
    isListedInCatalog,
    isTogglingCatalogVisibility,
    isCreating,
    isPublishing,
    partyLifecycleState,
    isTransitioningLifecycle,
    pendingLifecycleTransition,
    isCheckingParty,
    serverError,
    serverUnreachable,
    isReconnecting,
    lastManualCheckFailed,
    themeAccess,
    isThemeAccessLoading,
    themeAccessErrorMessage,
    themeEntitlementModal,
    setPartyName,
    setPartyTitle,
    setPartySubtitle,
    setEventDateTime,
    setDescription,
    setPlace,
    setCity,
    setSchedule,
    setShortDescription,
    setExternalLinkUrl,
    setExternalLinkText,
    setDanceTags,
    setIsListedInCatalog,
    setThemeEntitlementModal,
  } = usePartyWorkspaceStore((state) => ({
    partyName: state.partyName,
    partyTitle: state.partyTitle,
    partySubtitle: state.partySubtitle,
    themeId: state.themeId,
    customizationSettings: state.customizationSettings,
    eventDateTime: state.eventDateTime,
    eventEndDateTime: state.eventEndDateTime,
    description: state.description,
    place: state.place,
    city: state.city,
    schedule: state.schedule,
    timeZone: state.timeZone,
    shortDescription: state.shortDescription,
    externalLinkUrl: state.externalLinkUrl,
    externalLinkText: state.externalLinkText,
    danceTags: state.danceTags,
    isListedInCatalog: state.isListedInCatalog,
    isTogglingCatalogVisibility: state.isTogglingCatalogVisibility,
    isCreating: state.isCreating,
    isPublishing: state.isPublishing,
    partyLifecycleState: state.partyLifecycleState,
    isTransitioningLifecycle: state.isTransitioningLifecycle,
    pendingLifecycleTransition: state.pendingLifecycleTransition,
    isCheckingParty: state.isCheckingParty,
    serverError: state.serverError,
    serverUnreachable: state.serverUnreachable,
    isReconnecting: state.isReconnecting,
    lastManualCheckFailed: state.lastManualCheckFailed,
    themeAccess: state.themeAccess,
    isThemeAccessLoading: state.isThemeAccessLoading,
    themeAccessErrorMessage: state.themeAccessErrorMessage,
    themeEntitlementModal: state.themeEntitlementModal,
    setPartyName: state.setPartyName,
    setPartyTitle: state.setPartyTitle,
    setPartySubtitle: state.setPartySubtitle,
    setEventDateTime: state.setEventDateTime,
    setDescription: state.setDescription,
    setPlace: state.setPlace,
    setCity: state.setCity,
    setSchedule: state.setSchedule,
    setShortDescription: state.setShortDescription,
    setExternalLinkUrl: state.setExternalLinkUrl,
    setExternalLinkText: state.setExternalLinkText,
    setDanceTags: state.setDanceTags,
    setIsListedInCatalog: state.setIsListedInCatalog,
    setThemeEntitlementModal: state.setThemeEntitlementModal,
  }));

  const { openModal } = useUIStore((state) => ({
    openModal: state.openModal,
  }));

  const playlistState = usePartyPlaylistState();
  const effects = usePartyWorkspaceEffects(isAuth, networkEnabled);

  const playlistBuildParams = useMemo(
    () => ({
      streamingSource: playlistState.streamingSource,
      aimpPlaylistSnapshot: playlistState.aimpPlaylistSnapshot,
      items: playlistState.items,
      partyTrackDisplay: playlistState.partyTrackDisplay,
    }),
    [
      playlistState.streamingSource,
      playlistState.aimpPlaylistSnapshot,
      playlistState.items,
      playlistState.partyTrackDisplay,
    ],
  );

  const serverEffects = useMemo(
    () => ({
      loadThemeAccess: effects.loadThemeAccess,
      checkPartyExists: effects.checkPartyExists,
      startReconnectTimer: effects.startReconnectTimer,
      isNetworkEnabled: () => networkEnabled,
    }),
    [
      effects.loadThemeAccess,
      effects.checkPartyExists,
      effects.startReconnectTimer,
      networkEnabled,
    ],
  );

  const serverActions = usePartyServerActions(isAuth, playlistBuildParams, serverEffects);

  return useMemo(
    () => ({
      isAuth,
      isClientOutdated,
      clientRequiredVersion,
      isCheckingParty,
      serverUnreachable,
      isReconnecting,
      lastManualCheckFailed,
      handleManualReconnect: effects.handleManualReconnect,
      meta,
      partyTrackDisplay: playlistState.partyTrackDisplay,
      setPartyTrackDisplaySettings,
      partyName,
      partyTitle,
      partySubtitle,
      themeId,
      customizationSettings,
      eventDateTime,
      eventEndDateTime,
      description,
      place,
      city,
      schedule,
      timeZone,
      shortDescription,
      externalLinkUrl,
      externalLinkText,
      danceTags,
      isListedInCatalog,
      isTogglingCatalogVisibility,
      isCreating,
      isPublishing,
      partyLifecycleState,
      isTransitioningLifecycle,
      pendingLifecycleTransition,
      serverError,
      themeAccess,
      isThemeAccessLoading,
      themeAccessErrorMessage,
      themeEntitlementModal,
      setPartyName,
      setPartyTitle,
      setPartySubtitle,
      setEventDateTime,
      setDescription,
      setPlace,
      setCity,
      setSchedule,
      setShortDescription,
      setExternalLinkUrl,
      setExternalLinkText,
      setDanceTags,
      setIsListedInCatalog,
      setThemeEntitlementModal,
      handleThemeChange: effects.handleThemeChange,
      handleCustomizationSettingsChange: effects.handleCustomizationSettingsChange,
      handleEventEndDateTimeChange: effects.handleEventEndDateTimeChange,
      handleTimeZoneChange: effects.handleTimeZoneChange,
      handleCreateParty: serverActions.handleCreateParty,
      handlePublish: serverActions.handlePublish,
      handleCopyUrl: serverActions.handleCopyUrl,
      handleCatalogVisibilityChange: serverActions.handleCatalogVisibilityChange,
      handleRetry: effects.handleRetry,
      handleResetAndCreateNewParty: effects.handleResetAndCreateNewParty,
      handleLifecycleTransition: serverActions.handleLifecycleTransition,
      openModal,
      lockedThemeInfos: effects.lockedThemeInfos,
      visibleThemeIds: effects.visibleThemeIds,
      previewPlaylistData: playlistState.previewPlaylistData,
      playbackState: playlistState.playbackState,
    }),
    [
      isAuth,
      isClientOutdated,
      clientRequiredVersion,
      isCheckingParty,
      serverUnreachable,
      isReconnecting,
      lastManualCheckFailed,
      effects.handleManualReconnect,
      meta,
      playlistState.partyTrackDisplay,
      setPartyTrackDisplaySettings,
      partyName,
      partyTitle,
      partySubtitle,
      themeId,
      customizationSettings,
      eventDateTime,
      eventEndDateTime,
      description,
      place,
      city,
      schedule,
      timeZone,
      shortDescription,
      externalLinkUrl,
      externalLinkText,
      danceTags,
      isListedInCatalog,
      isTogglingCatalogVisibility,
      isCreating,
      isPublishing,
      partyLifecycleState,
      isTransitioningLifecycle,
      pendingLifecycleTransition,
      serverError,
      themeAccess,
      isThemeAccessLoading,
      themeAccessErrorMessage,
      themeEntitlementModal,
      setPartyName,
      setPartyTitle,
      setPartySubtitle,
      setEventDateTime,
      setDescription,
      setPlace,
      setCity,
      setSchedule,
      setShortDescription,
      setExternalLinkUrl,
      setExternalLinkText,
      setDanceTags,
      setIsListedInCatalog,
      setThemeEntitlementModal,
      effects.handleThemeChange,
      effects.handleCustomizationSettingsChange,
      effects.handleEventEndDateTimeChange,
      effects.handleTimeZoneChange,
      serverActions.handleCreateParty,
      serverActions.handlePublish,
      serverActions.handleCopyUrl,
      serverActions.handleCatalogVisibilityChange,
      effects.handleRetry,
      effects.handleResetAndCreateNewParty,
      serverActions.handleLifecycleTransition,
      openModal,
      effects.lockedThemeInfos,
      effects.visibleThemeIds,
      playlistState.previewPlaylistData,
      playlistState.playbackState,
    ],
  );
}
