export const ROUTES = {
  HOME: '/',
  PARTY_VIEW: (shortCode: string) => `/party/${shortCode}`,
  PARTY_INFO: (shortCode: string) => `/party/${shortCode}/info`,
  LOGIN: '/login',
  REGISTER: '/register',
  OAUTH_COMPLETE: '/oauth/complete',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  CABINET: '/cabinet',
  ADMIN_ROOT: '/admin',
  ADMIN_ORGANIZERS: '/admin/organizers',
  ADMIN_ORGANIZER_DETAIL: (organizerId: string) => `/admin/organizers/${organizerId}`,
  PRIVACY: '/privacy',
  PRIVACY_ARCHIVE: (version: string) => `/privacy/v/${version}`,
  CONSENT: '/consent',
  CONSENT_ARCHIVE: (version: string) => `/consent/v/${version}`,
  TERMS: '/terms',
  TERMS_ARCHIVE: (version: string) => `/terms/v/${version}`,
  COOKIES: '/cookies',
  COOKIES_ARCHIVE: (version: string) => `/cookies/v/${version}`,
  LEGAL: '/legal',
} as const;
